name: CI

on:
   push:
     branches: [ main ]
   pull_request:
      branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v
    - name: init,build
        run:|
        git submodule update --init
        hugo -D
    - name: Deploy to Server
        uses:easingthemes/ssh-deploy@v2.1.5
        env:|
            SSH_PRIVATE_KEY:${{ secrets.SERVER_SSH_KEY }}
            ARGS:"-rltgoDzvO --delete"
            SOURCE:"./public"
            REMOTE_HOST:${{ secrets.REMOTE_HOST }}
            REMOTE_USER:${{ secrets.REMOTE_USER }}
            TARGET:${{ secrets.REMOTE_TARGET }}
